### PR TITLE
Try gdImageCrop + gdImageScale instead of legacy gdImageCopyResampled

### PR DESCRIPTION
**Pull request by lilith**
gdImageCopyResampled is retained for compatibility purposes, but in theory should be quite a bit slower than gdImageScale (which defaults to bilinear).

Also, gdImageSharpen is extremely inefficient, and should be avoided in favor of a composed scaling and sharpening weight kernel (which, unfortunately, isn't in the mainstream release yet).

vips-bench doesn't seem to work on OS X (`/usr/bin/time: illegal option -- f usage: time [-lp] command.`, and there are many warnings when linking against vips 7.42.1). I can't run the benchmark myself, but I think these changes may help.

### CODE REVIEW

**Comment by AGenchev** [comment]
what is the purpose of these improvements - to create fair benchmark with GD ?
if so, then do you "benchmark" the quality of the resampled image ? 
I mean that the speed ups often come at a cost, so if you compare the pixel ARGB values differences to a best quality/reference implementation for the given filtering method, then you'll be able to tell whether the quality is OK or not.

**Comment by lilith** [comment]
Both LibGD and libvips differ considerably from reference software such as ImageWorsener. Ideally they would match with only off-by-one errors.

**Comment by AGenchev** [comment]
What size are the images in your test ? 
I created a dHash function which needs 9x8 thumbnail. I run the code on a 416x416 pixels jpeg. Together with the JPEG file load time, the GD based solution works much faster than the vips based one. 
The difference is that in vips I create max 128x128 thumbnail, convert it to gray then resample to 9x8 and in GD I use gdImageCopyResampled for direct TrueColor resampling to 9x8 of the whole image, then I convert to gray on pixel read with floating-point multiply.

**Comment by jcupitt** [comment]
git master libvips has some improvements to downsample accuracy, it might be worth testing that.

**Pull request merged**
